require('dotenv').config();
const { Client } = require('pg');
const client = new Client({ connectionString: process.env.DATABASE_URL + '?sslmode=require' });
async function clean() {
  try {
    await client.connect();
    // Wipe fake telemetry and scans
    await client.query('DELETE FROM "SensorReading"');
    await client.query('DELETE FROM "QRScan"');
    
    // Wipe fake demo hive and devices generated by the script
    await client.query('DELETE FROM "Hive" WHERE location LIKE \'%Apiary%\'');
    
    console.log('Demo sensor data and demo hives wiped successfully!');
  } catch (e) {
    console.error('Error cleaning DB:', e);
  } finally {
    await client.end();
  }
}
clean();
